name: "vk-recorder"

on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: node recorder/dist/main.js
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        VK_TARGET_USER_ID: ${{ secrets.VK_TARGET_USER_ID }}
        VK_ACCESS_TOKEN: ${{ secrets.VK_ACCESS_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DYNAMODB_TABLE_NAME: ${{ secrets.DYNAMODB_TABLE_NAME }}